import '../models/models.dart';

const List<InsuranceCompany> insuranceCompanies = const [
  InsuranceCompany(name: 'NUEVA EPS', id: 1),
  InsuranceCompany(name: 'FUNDACION AVANZAR FOS', id: 2),
  InsuranceCompany(name: 'UT RED INTEGRADA', id: 3),
  InsuranceCompany(name: 'FAMISANAR', id: 4),
  InsuranceCompany(name: 'COOMEVA PREPAGADA', id: 5),
  InsuranceCompany(name: 'COOMEVA EPS', id: 6),
  InsuranceCompany(name: 'SEGUROS BOLIVAR MP', id: 7),
  InsuranceCompany(name: 'UNIVERSIDAD INDUSTRIAL DE SANTANDER', id: 8),
  InsuranceCompany(name: 'UISALUD', id: 9),
  InsuranceCompany(name: 'COLMEDICA MEDICINA PREPAGADA', id: 10),
  InsuranceCompany(name: 'CLINICA CHICAMOCHA', id: 11),
  InsuranceCompany(name: 'ALLIANZ', id: 12),
  InsuranceCompany(name: 'COLPATRIA ARL', id: 13),
  InsuranceCompany(name: 'MED PLUS', id: 14),
  InsuranceCompany(name: 'SURAMERICANA MP', id: 15),
  InsuranceCompany(name: 'COLSANITAS', id: 16),
  InsuranceCompany(name: 'MEDISANITAS', id: 17),
  InsuranceCompany(name: 'SALUD TOTAL', id: 18),
  InsuranceCompany(name: 'FUNDACION OFTALMOLOGICA DE SANTANDER', id: 19),
  InsuranceCompany(name: 'INSTITUTO DEL CORAZON', id: 20),
  InsuranceCompany(name: 'SEGUROS DEL ESTADO SOAT', id: 21),
  InsuranceCompany(name: 'MAPFRE SOAT', id: 22),
  InsuranceCompany(name: 'LA EQUIDAD SOAT', id: 23),
  InsuranceCompany(name: 'ZURICH SOAT', id: 24),
  InsuranceCompany(name: 'LIBERTY SOAT', id: 25),
  InsuranceCompany(name: 'ASEGURADORA SOLIDARIA SOAT', id: 26),
  InsuranceCompany(name: 'SEGUROS BOLIVAR SOAT', id: 27),
  InsuranceCompany(name: 'SURAMERICANA SOAT', id: 28),
  InsuranceCompany(name: 'AXA COLPATRIA SOAT', id: 29),
  InsuranceCompany(name: 'LA PREVISORA SOAT', id: 30),
  InsuranceCompany(name: 'COMPAÑÍA MUNDIAL SOAT', id: 31),
  InsuranceCompany(name: 'ADRES', id: 32),
];
